package org.codewithmagret.rest.product;

import jakarta.persistence.*;

/**
 * Represents a product entity in the system
 * This class is mapped to a database table using JPA annotations.
 * Each product has a unique ID, name, description, and price.
 * The ID is automatically generated by the database and serves as the
 * primary key for the product.
 */
@Entity
@Table(name = "product")
public class Product {
    /**
     * The unique identifier for the product.
     * This field is automatically generated by the database and serves as the primary key for the product.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the product
     * This field is required and represents the product's name.
     */
    private String name;

    /**
     * The available stock quantity of the product.
     */
    private int stock;

    /**
     * The price of the product.
     * This field represents the price of the product.
     */
    private double price;

    /**
     * Parameterized Constructor of Product Class
     *
     * @param id id of the product
     * @param name name of the product
     * @param stock description of the product
     * @param price price of the product
     */
    public Product(Long id, String name, int stock, double price) {
        this.id = id;
        this.name = name;
        this.stock = stock;
        this.price = price;
    }

    /**
     * Default Constructor of the product class
     */
    public Product() {}

    /**
     * Gets the unique identifier of the product.
     * @return ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name of the product
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the product
     * @param name name of the product
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the available stock quantity.
     *
     * @return the stock quantity
     */
    public int getStock() {
        return stock;
    }

    /**
     * Sets the available stock quantity.
     *
     * @param stock the stock quantity
     */
    public void setStock(int stock) {
        this.stock = stock;
    }

    /**
     * Gets price of the product
     * @return price of the product
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets price of the product
     * @param price price of the product
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * toString method which helps to print a readable format of the object
     * @return string representation of the object
     */
    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", stock='" + stock + '\'' +
                ", price=" + price +
                '}';
    }


}