package org.codewithmagret.rest.customer;

import jakarta.persistence.*;

/**
 * Represents a customer entity in the system
 * This class is mapped to a database table using JPA annotations.
 * Each customer has a unique ID, name and email.
 * The ID is automatically generated by the database and serves as the
 * primary key for the customer.
 */
@Entity
public class Customer {
    /**
     * The unique identifier for the customer.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * This field represents the name of the customer.
     */
    private String name;

    /**
     * This field represents the email of the customer.
     */
    private String email;

    /**
     * Default Constructor of the customer class
     */
    public Customer() {
    }

    /**
     * Parameterized constructor of customer class
     * @param id id of the customer
     * @param name name of the customer
     * @param email email of the customer
     */
    public Customer(Long id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    /**
     * Gets the unique identifier of the customer
     * @return ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name of the customer
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the customer
     * @param name name of the customer
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the email of the customer
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email of the customer
     * @param email email of the customer
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * toString method which helps to print a readable format of the object
     * @return string representation of the object
     */
    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}