package org.codewithmagret.rest.orders;

import jakarta.persistence.*;
import org.codewithmagret.rest.customer.Customer;

import java.time.LocalDate;

/**
 * Represents a order entity in the system
 * This class is mapped to a database table using JPA annotations.
 * Each order has a unique ID, orderDate, priorityLevel and a reference to the customer who placed the order.
 * The ID is automatically generated by the database and serves as the
 * primary key for the order.
 */
@Entity
@Table(name = "orders")
public class Order {
    /**
     * The unique identifier for the customer.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The date of the order
     */
    private LocalDate orderDate;

    /**
     * The priority level of the order
     * This field represents the priority level of the order, with a value between 1 and 10.
     */
    private Integer priorityLevel; // (1-10)

    /**
     * Many-to-One relationship between Order and Customer
     * An order is placed by one customer, but a customer can place multiple orders.
     */
    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;

    /**
     * Default constructor of the order class
     */
    public Order() {
    }

    /**
     * Parameterized constructor of order class
     *
     * @param orderDate date of order
     * @param priorityLevel priority level of order
     * @param customer customer who placed the order
     */
    public Order(LocalDate orderDate, int priorityLevel, Customer customer) {
        this.orderDate = orderDate;
        this.priorityLevel = priorityLevel;
        this.customer = customer;
    }

    /**
     * Gets the unique identifier of the customer
     * @return ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets order date
     * @return order date
     */
    public LocalDate getOrderDate() {
        return orderDate;
    }

    /**
     * Sets order date
     * @param orderDate order date
     */
    public void setOrderDate(LocalDate orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * Gets priority level of order
     * @return priority level
     */
    public int getPriorityLevel() {
        return priorityLevel;
    }

    /**
     * Sets priority level of order
     * @param priorityLevel priority level
     */
    public void setPriorityLevel(int priorityLevel) {
        this.priorityLevel = priorityLevel;
    }

    /**
     * Gets customer who placed order
     * @return customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets customer who placed order
     * @param customer customer
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * toString method which helps to print a readable format of the object
     * @return string representation of the object
     */
    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", orderDate=" + orderDate +
                ", priorityLevel=" + priorityLevel +
                ", customer=" + customer +
                '}';
    }
}